export enum Topics {
  NODE_JS = 'Node.js',
  JAVASCRIPT = 'JavaScript',
  EXPRESS_JS = 'Express.js',
  TYPESCRIPT = 'TypeScript',
  NEST_JS = 'Nest.js',
  DATABASES = 'Databases',
  PRINCIPLES = 'Principles',
  GIT = 'Git',
  GRAPHQL = 'GraphQL',
  AWS = 'AWS',
  DOCKER = 'Docker',
  MICROSERVICES = 'Microservices',
  PATTERNS = 'Patterns',
  DYNAMODB = 'DynamoDB',
}
